### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by Evgen-Viktorovich** [WhiteHeadbanger/rpg#1]
Hi, sorry for disturb, this is not issue for you, just want to ask how much time did you spend to get first contract for BTFS.
https://github.com/TRON-US/go-btfs
Also what score and uptime need to get first contact?
Also how much free space did you have for this system?
Many thanks and best regards.

**Comment by WhiteHeadbanger** [comment]
Hi, didn't see this.

I spent like 1 week for my first contract.
I would say starting from 8/10 score
And I have 64GB for it
